### ISSUE TITLE
你好，请问你是买了恩培的网课吗？

### ISSUE THREAD

**Issue by Healedtalk** [z-z-zhao/-#1]
你好我想问一下，你是不是买了恩培的网课？我想要一下恩培答疑群里的网盘资料，若能答复，感激不敬·！

**Comment by z-z-zhao** [comment]
你好，很抱歉我不能这样做，因为这个是有版权。

**Comment by Healedtalk** [comment]
> 你好，很抱歉我不能这样做，因为这个是有版权。

你买的是tensorrt那个吗？
还是说他们的两个课程都买了？
保存在你自己网盘，在网盘发一下，可以吗？

**Comment by Healedtalk** [comment]
我要的只是网盘资料，不是网课
